### ISSUE TITLE
[Feature Suggestion] Manual dark-light switch

### ISSUE THREAD

**Issue by noyannus** [oskarsh/Yin-Yang#155]
Two buttons to switch manually between `dark` and `light` would be very helpful for testing the chosen themes. Also for debugging, I guess.
Like so, for example:
`[ Dark ]  [ Light ]  [ Apply ]  [Cancel]`

**Comment by l0drex** [comment]
They were present in an older version, but I removed them because they kinda didnt make much sense - this program is for changing the theme automatically. If you want to debug, you can use yin-yang from the command line:

```shell
yin-yang --toggle
```

**Comment by noyannus** [comment]
Ah, good to know. Thanks!

**Comment by sinux-l5d** [comment]
Hi @l0drex I'm surprised because that looks like a feature regression to me: I was using Yin Yang only this way, because I mostly use dark theme except in some specific cases.

I noticed that change yesterday, after yay was complaining that remote repo was different from local one, and had to reinstall yin-yang.

Are you sure a manual switch is not something users want?

**Comment by l0drex** [comment]
Ok, that's a use case I didn't think of. I will re-add them in the next version.
I thought these were just for testing, so kinda unnecessary for users.
