### ISSUE TITLE
Fail to install in kubuntu 20.04

### ISSUE THREAD

**Issue by vroger11** [oskarsh/Yin-Yang#86]
After cloning the repo, I get the following error:
install.sh: 3: set: Illegal option -o pipefail

Any suggestions?

**Comment by l0drex** [comment]
Try to use just
```bash
./install.sh
```
instead of `sh ./install.sh`

**Comment by vroger11** [comment]
It worked using `./install.sh` instead of `sh install.sh`. My default shell is bash, and I was not looking but the first line of `install.sh` is:
```bash
#!/bin/bash
```
The doc should be modified accordingly as sh is not the same shell as bash

**Comment by l0drex** [comment]
Yeah, the wiki is pretty outdated on many pages.
@oskarsh If you feel like you could need some help there, you can add me as a contributor and I can update the wiki. Or alternatively, I think you can also give everyone write access for the wiki.

However, glad that it worked! If your problem is now resolved, feel free to close this issue.

**Comment by vroger11** [comment]
I think the issue should be closed when the readme is fixed. It can help others while it is not done.

**Comment by oskarsh** [comment]
@l0drex added you as a collab feel free to do any modifications and update the wiki if you like

**Comment by l0drex** [comment]
Yes, thank you! I will start by copying the documentation from the pull requests into the contributing section.
